(* This file is generated by Why3's Coq driver *)
(* Beware! Only edit allowed sections below    *)
Require Import BuiltIn.
Require BuiltIn.
Require HighOrd.
Require map.Map.

Axiom t : Type.
Parameter t_WhyType : WhyType t.
Existing Instance t_WhyType.

Axiom u : Type.
Parameter u_WhyType : WhyType u.
Existing Instance u_WhyType.

Parameter rel: t -> u -> Prop.

Axiom Deter :
  forall (x:t), forall (y:u) (z:u), rel x y -> rel x z -> (y = z).

Axiom Total : forall (x:t), exists y:u, rel x y.

(* Why3 assumption *)
Definition map_graph (m:t -> u) : Prop :=
  forall (x:t), forall (y:u), ((m x) = y) <-> rel x y.

(* Why3 goal *)
Theorem ex_map : exists m:t -> u, map_graph m.
Proof.
destruct (Logic.ClassicalEpsilon.choice rel Total) as [f H].
exists f.
split; intro F.
- rewrite <- F. apply H.
- apply eq_sym. apply Deter with (x := x). apply F. apply H.
Qed.

