###################################################################
# Copyright (C) 2020 Alain Giorgetti                              #
# FEMTO-ST institute                                              #
###################################################################

###################################################################
#  This software is distributed under the terms of the GNU Lesser #
#  General Public License version 2.1                             #
###################################################################

# src/ABF20/Makefile

.PHONY: doc clean

doc:
	why3 session html ../ABF20.mlw
	@echo firefox ABF20/why3session.html

clean:
	rm -f *.bak